editor:
  name: Редактор
  description: Редактор
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      form: ~/themes/intgolos/partials/components/editor/_.yaml

intro:
  name: Интро
  description: Интро
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      form: ~/themes/intgolos/partials/components/intro/_.yaml

about_us:
  name: О нас
  description: О нас
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      form: ~/themes/intgolos/partials/components/about_us/_.yaml

steps:
  name: Шаги
  description: Шаги
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      form: ~/themes/intgolos/partials/components/steps/_.yaml

offer:
  name: Оффер
  description: Оффер
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      form: ~/themes/intgolos/partials/components/offer/_.yaml

voting:
  name: Голосование
  description: Голосование
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      form: ~/themes/intgolos/partials/components/voting/_.yaml

information:
  name: Информация
  description: Информация
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      form: ~/themes/intgolos/partials/components/information/_.yaml

timer:
  name: Таймер
  description: Таймер
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      form: ~/themes/intgolos/partials/components/timer/_.yaml

season_winners:
  name: Победители сезона
  description: Оффер
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      form: ~/themes/intgolos/partials/components/season_winners/_.yaml

month_winners:
  name: Победители месяца
  description: Победители месяца
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      form: ~/themes/intgolos/partials/components/month_winners/_.yaml

reports:
  name: Отчеты
  description: Отчеты
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      form: ~/themes/intgolos/partials/components/reports/_.yaml

subscribe:
  name: Подписаться
  description: Подписаться
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      form: ~/themes/intgolos/partials/components/subscribe/_.yaml

our_services:
  name: Наши услуги
  description: Наши услуги
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      form: ~/themes/intgolos/partials/components/our_services/_.yaml

contacts:
  name: Контакты
  description: Контакты
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      form: ~/themes/intgolos/partials/components/contacts/_.yaml

modal:
  name: Модальное окно
  description: Модальное окно
  icon: icon-list-alt
  fields:
    content:
      type: nestedform
      form: ~/themes/intgolos/partials/components/modal/_.yaml
